//
// Generated file, do not edit! Created by opp_msgtool 6.2 from /home/helen/omnetpp-6.2.0/centralized/centralized/report.msg.
//

#ifndef __OMNETPP_REPORT_M_H
#define __OMNETPP_REPORT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace omnetpp {

class ReportMessage;

}  // namespace omnetpp


namespace omnetpp {

/**
 * Class generated from <tt>/home/helen/omnetpp-6.2.0/centralized/centralized/report.msg:16</tt> by opp_msgtool.
 * <pre>
 * message ReportMessage
 * {
 *     string SenderID;          // 发送者ID
 *     string Content;           // 报告内容
 *     string HashValue;         // 哈希值
 *     long Timestamp;           // 时间戳
 *     string Signature;
 *     string Senderpublickey;
 * }
 * </pre>
 */
class ReportMessage : public ::omnetpp::cMessage
{
  protected:
    opp_string SenderID;
    opp_string Content;
    opp_string HashValue;
    long Timestamp = 0;
    opp_string Signature;
    opp_string Senderpublickey;

  private:
    void copy(const ReportMessage& other);

  protected:
    bool operator==(const ReportMessage&) = delete;

  public:
    ReportMessage(const char *name=nullptr, short kind=0);
    ReportMessage(const ReportMessage& other);
    virtual ~ReportMessage();
    ReportMessage& operator=(const ReportMessage& other);
    virtual ReportMessage *dup() const override {return new ReportMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSenderID() const;
    virtual void setSenderID(const char * SenderID);

    virtual const char * getContent() const;
    virtual void setContent(const char * Content);

    virtual const char * getHashValue() const;
    virtual void setHashValue(const char * HashValue);

    virtual long getTimestamp() const;
    virtual void setTimestamp(long Timestamp);

    virtual const char * getSignature() const;
    virtual void setSignature(const char * Signature);

    virtual const char * getSenderpublickey() const;
    virtual void setSenderpublickey(const char * Senderpublickey);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ReportMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ReportMessage& obj) {obj.parsimUnpack(b);}


}  // namespace omnetpp


namespace omnetpp {

template<> inline omnetpp::ReportMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::ReportMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __OMNETPP_REPORT_M_H

