//
// Generated file, do not edit! Created by opp_msgtool 6.2 from message.msg.
//

#ifndef __OMNETPP_MESSAGE_M_H
#define __OMNETPP_MESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace omnetpp {

class ReportMessage;
class JoinReq;
class JoinVerifyReq;
class JoinAck;
class PeerJoinReq;
class PeerJoinVerifyReq;
class PeerJoinAck;
class SyncLedgerReq;
class ReportEntry;
class SyncBlockMsg;
class LeaveReq;
class LeaveAck;
class PeerLeaveReq;
class ReJoin;
class PeerLeaveAck;
class VerifyMessage;
class PrePrepareMsg;
class PrepareMsg;
class CommitMsg;
class BlockMsg;

}  // namespace omnetpp


namespace omnetpp {

/**
 * Class generated from <tt>message.msg:15</tt> by opp_msgtool.
 * <pre>
 * message ReportMessage
 * {
 *     string SenderID;          // 发送者ID
 *     string Content;           // 报告内容
 *     string HashValue;         // 哈希值
 *     long Timestamp;           // 时间戳
 *     string Signature;
 *     string Senderpublickey;
 * }
 * 
 * // =======================
 * // Join / Leave control messages
 * // =======================
 * </pre>
 */
class ReportMessage : public ::omnetpp::cMessage
{
  protected:
    opp_string SenderID;
    opp_string Content;
    opp_string HashValue;
    long Timestamp = 0;
    opp_string Signature;
    opp_string Senderpublickey;

  private:
    void copy(const ReportMessage& other);

  protected:
    bool operator==(const ReportMessage&) = delete;

  public:
    ReportMessage(const char *name=nullptr, short kind=0);
    ReportMessage(const ReportMessage& other);
    virtual ~ReportMessage();
    ReportMessage& operator=(const ReportMessage& other);
    virtual ReportMessage *dup() const override {return new ReportMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSenderID() const;
    virtual void setSenderID(const char * SenderID);

    virtual const char * getContent() const;
    virtual void setContent(const char * Content);

    virtual const char * getHashValue() const;
    virtual void setHashValue(const char * HashValue);

    virtual long getTimestamp() const;
    virtual void setTimestamp(long Timestamp);

    virtual const char * getSignature() const;
    virtual void setSignature(const char * Signature);

    virtual const char * getSenderpublickey() const;
    virtual void setSenderpublickey(const char * Senderpublickey);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ReportMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ReportMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:29</tt> by opp_msgtool.
 * <pre>
 * // device -> TopoManager：加入请求（携带设备ID + 报告）
 * message JoinReq
 * {
 *     int deviceId;
 *     ReportMessage rm;
 *     int cpu;
 *     int memory;
 *     int IO;
 *     simtime_t sendTime;   // 发送时刻（用于统计加入耗时）
 * }
 * </pre>
 */
class JoinReq : public ::omnetpp::cMessage
{
  protected:
    int deviceId = 0;
    ReportMessage rm;
    int cpu = 0;
    int memory = 0;
    int IO = 0;
    simtime_t sendTime = SIMTIME_ZERO;

  private:
    void copy(const JoinReq& other);

  protected:
    bool operator==(const JoinReq&) = delete;

  public:
    JoinReq(const char *name=nullptr, short kind=0);
    JoinReq(const JoinReq& other);
    virtual ~JoinReq();
    JoinReq& operator=(const JoinReq& other);
    virtual JoinReq *dup() const override {return new JoinReq(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getDeviceId() const;
    virtual void setDeviceId(int deviceId);

    virtual const ReportMessage& getRm() const;
    virtual ReportMessage& getRmForUpdate() { return const_cast<ReportMessage&>(const_cast<JoinReq*>(this)->getRm());}
    virtual void setRm(const ReportMessage& rm);

    virtual int getCpu() const;
    virtual void setCpu(int cpu);

    virtual int getMemory() const;
    virtual void setMemory(int memory);

    virtual int getIO() const;
    virtual void setIO(int IO);

    virtual simtime_t getSendTime() const;
    virtual void setSendTime(simtime_t sendTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const JoinReq& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, JoinReq& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:39</tt> by opp_msgtool.
 * <pre>
 * // TopoManager -> nearest peer：验证请求（把加入请求转发给最近 peer）
 * message JoinVerifyReq
 * {
 *     int deviceId;
 *     int assignedPeerId;   // 最近 peer id（deviceId % peer_num）
 *     ReportMessage rm;
 *     simtime_t sendTime;   // 保留原始发送时刻（便于链路端到端统计）
 * }
 * </pre>
 */
class JoinVerifyReq : public ::omnetpp::cMessage
{
  protected:
    int deviceId = 0;
    int assignedPeerId = 0;
    ReportMessage rm;
    simtime_t sendTime = SIMTIME_ZERO;

  private:
    void copy(const JoinVerifyReq& other);

  protected:
    bool operator==(const JoinVerifyReq&) = delete;

  public:
    JoinVerifyReq(const char *name=nullptr, short kind=0);
    JoinVerifyReq(const JoinVerifyReq& other);
    virtual ~JoinVerifyReq();
    JoinVerifyReq& operator=(const JoinVerifyReq& other);
    virtual JoinVerifyReq *dup() const override {return new JoinVerifyReq(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getDeviceId() const;
    virtual void setDeviceId(int deviceId);

    virtual int getAssignedPeerId() const;
    virtual void setAssignedPeerId(int assignedPeerId);

    virtual const ReportMessage& getRm() const;
    virtual ReportMessage& getRmForUpdate() { return const_cast<ReportMessage&>(const_cast<JoinVerifyReq*>(this)->getRm());}
    virtual void setRm(const ReportMessage& rm);

    virtual simtime_t getSendTime() const;
    virtual void setSendTime(simtime_t sendTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const JoinVerifyReq& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, JoinVerifyReq& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:46</tt> by opp_msgtool.
 * <pre>
 * message JoinAck
 * {
 *     int deviceId;
 *     int peerId;
 *     bool success;
 *     simtime_t time;
 * }
 * </pre>
 */
class JoinAck : public ::omnetpp::cMessage
{
  protected:
    int deviceId = 0;
    int peerId = 0;
    bool success = false;
    simtime_t time = SIMTIME_ZERO;

  private:
    void copy(const JoinAck& other);

  protected:
    bool operator==(const JoinAck&) = delete;

  public:
    JoinAck(const char *name=nullptr, short kind=0);
    JoinAck(const JoinAck& other);
    virtual ~JoinAck();
    JoinAck& operator=(const JoinAck& other);
    virtual JoinAck *dup() const override {return new JoinAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getDeviceId() const;
    virtual void setDeviceId(int deviceId);

    virtual int getPeerId() const;
    virtual void setPeerId(int peerId);

    virtual bool getSuccess() const;
    virtual void setSuccess(bool success);

    virtual simtime_t getTime() const;
    virtual void setTime(simtime_t time);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const JoinAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, JoinAck& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:53</tt> by opp_msgtool.
 * <pre>
 * message PeerJoinReq
 * {
 *     int peerId;          // 3
 *     ReportMessage rm;
 *     int cpu;
 *     int memory;
 *     int IO;
 *     simtime_t sendTime;
 * }
 * </pre>
 */
class PeerJoinReq : public ::omnetpp::cMessage
{
  protected:
    int peerId = 0;
    ReportMessage rm;
    int cpu = 0;
    int memory = 0;
    int IO = 0;
    simtime_t sendTime = SIMTIME_ZERO;

  private:
    void copy(const PeerJoinReq& other);

  protected:
    bool operator==(const PeerJoinReq&) = delete;

  public:
    PeerJoinReq(const char *name=nullptr, short kind=0);
    PeerJoinReq(const PeerJoinReq& other);
    virtual ~PeerJoinReq();
    PeerJoinReq& operator=(const PeerJoinReq& other);
    virtual PeerJoinReq *dup() const override {return new PeerJoinReq(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getPeerId() const;
    virtual void setPeerId(int peerId);

    virtual const ReportMessage& getRm() const;
    virtual ReportMessage& getRmForUpdate() { return const_cast<ReportMessage&>(const_cast<PeerJoinReq*>(this)->getRm());}
    virtual void setRm(const ReportMessage& rm);

    virtual int getCpu() const;
    virtual void setCpu(int cpu);

    virtual int getMemory() const;
    virtual void setMemory(int memory);

    virtual int getIO() const;
    virtual void setIO(int IO);

    virtual simtime_t getSendTime() const;
    virtual void setSendTime(simtime_t sendTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PeerJoinReq& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PeerJoinReq& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:63</tt> by opp_msgtool.
 * <pre>
 * message PeerJoinVerifyReq
 * {
 *     int peerId;
 *     ReportMessage rm;
 *     simtime_t sendTime;   // 保留原始发送时刻（便于链路端到端统计）
 * }
 * </pre>
 */
class PeerJoinVerifyReq : public ::omnetpp::cMessage
{
  protected:
    int peerId = 0;
    ReportMessage rm;
    simtime_t sendTime = SIMTIME_ZERO;

  private:
    void copy(const PeerJoinVerifyReq& other);

  protected:
    bool operator==(const PeerJoinVerifyReq&) = delete;

  public:
    PeerJoinVerifyReq(const char *name=nullptr, short kind=0);
    PeerJoinVerifyReq(const PeerJoinVerifyReq& other);
    virtual ~PeerJoinVerifyReq();
    PeerJoinVerifyReq& operator=(const PeerJoinVerifyReq& other);
    virtual PeerJoinVerifyReq *dup() const override {return new PeerJoinVerifyReq(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getPeerId() const;
    virtual void setPeerId(int peerId);

    virtual const ReportMessage& getRm() const;
    virtual ReportMessage& getRmForUpdate() { return const_cast<ReportMessage&>(const_cast<PeerJoinVerifyReq*>(this)->getRm());}
    virtual void setRm(const ReportMessage& rm);

    virtual simtime_t getSendTime() const;
    virtual void setSendTime(simtime_t sendTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PeerJoinVerifyReq& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PeerJoinVerifyReq& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:69</tt> by opp_msgtool.
 * <pre>
 * message PeerJoinAck
 * {
 *     int peerId;
 *     bool success;
 *     simtime_t time;
 * }
 * </pre>
 */
class PeerJoinAck : public ::omnetpp::cMessage
{
  protected:
    int peerId = 0;
    bool success = false;
    simtime_t time = SIMTIME_ZERO;

  private:
    void copy(const PeerJoinAck& other);

  protected:
    bool operator==(const PeerJoinAck&) = delete;

  public:
    PeerJoinAck(const char *name=nullptr, short kind=0);
    PeerJoinAck(const PeerJoinAck& other);
    virtual ~PeerJoinAck();
    PeerJoinAck& operator=(const PeerJoinAck& other);
    virtual PeerJoinAck *dup() const override {return new PeerJoinAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getPeerId() const;
    virtual void setPeerId(int peerId);

    virtual bool getSuccess() const;
    virtual void setSuccess(bool success);

    virtual simtime_t getTime() const;
    virtual void setTime(simtime_t time);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PeerJoinAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PeerJoinAck& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:76</tt> by opp_msgtool.
 * <pre>
 * message SyncLedgerReq
 * {
 *     int peerId;
 *     int fromHeight;
 *     simtime_t sendTime;
 * }
 * </pre>
 */
class SyncLedgerReq : public ::omnetpp::cMessage
{
  protected:
    int peerId = 0;
    int fromHeight = 0;
    simtime_t sendTime = SIMTIME_ZERO;

  private:
    void copy(const SyncLedgerReq& other);

  protected:
    bool operator==(const SyncLedgerReq&) = delete;

  public:
    SyncLedgerReq(const char *name=nullptr, short kind=0);
    SyncLedgerReq(const SyncLedgerReq& other);
    virtual ~SyncLedgerReq();
    SyncLedgerReq& operator=(const SyncLedgerReq& other);
    virtual SyncLedgerReq *dup() const override {return new SyncLedgerReq(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getPeerId() const;
    virtual void setPeerId(int peerId);

    virtual int getFromHeight() const;
    virtual void setFromHeight(int fromHeight);

    virtual simtime_t getSendTime() const;
    virtual void setSendTime(simtime_t sendTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SyncLedgerReq& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SyncLedgerReq& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:82</tt> by opp_msgtool.
 * <pre>
 * message ReportEntry
 * {
 *     ReportMessage rm;
 *     int state;   // 1=JOINED, 2=LEFT, 0/其他=NEW（按你现有映射）
 * }
 * </pre>
 */
class ReportEntry : public ::omnetpp::cMessage
{
  protected:
    ReportMessage rm;
    int state = 0;

  private:
    void copy(const ReportEntry& other);

  protected:
    bool operator==(const ReportEntry&) = delete;

  public:
    ReportEntry(const char *name=nullptr, short kind=0);
    ReportEntry(const ReportEntry& other);
    virtual ~ReportEntry();
    ReportEntry& operator=(const ReportEntry& other);
    virtual ReportEntry *dup() const override {return new ReportEntry(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const ReportMessage& getRm() const;
    virtual ReportMessage& getRmForUpdate() { return const_cast<ReportMessage&>(const_cast<ReportEntry*>(this)->getRm());}
    virtual void setRm(const ReportMessage& rm);

    virtual int getState() const;
    virtual void setState(int state);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ReportEntry& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ReportEntry& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:87</tt> by opp_msgtool.
 * <pre>
 * message SyncBlockMsg
 * {
 *     int peerId;
 *     int blockNum;
 *     string previousHash;
 *     string blockHash;
 *     long timestamp;
 *     int lastHeight;              // orderer 告诉对方目前链最新高度，便于判断何时结束
 *     ReportEntry entries[];       // 这个 block 的全部 reports（全量快照）
 * }
 * </pre>
 */
class SyncBlockMsg : public ::omnetpp::cMessage
{
  protected:
    int peerId = 0;
    int blockNum = 0;
    opp_string previousHash;
    opp_string blockHash;
    long timestamp = 0;
    int lastHeight = 0;
    ReportEntry *entries = nullptr;
    size_t entries_arraysize = 0;

  private:
    void copy(const SyncBlockMsg& other);

  protected:
    bool operator==(const SyncBlockMsg&) = delete;

  public:
    SyncBlockMsg(const char *name=nullptr, short kind=0);
    SyncBlockMsg(const SyncBlockMsg& other);
    virtual ~SyncBlockMsg();
    SyncBlockMsg& operator=(const SyncBlockMsg& other);
    virtual SyncBlockMsg *dup() const override {return new SyncBlockMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getPeerId() const;
    virtual void setPeerId(int peerId);

    virtual int getBlockNum() const;
    virtual void setBlockNum(int blockNum);

    virtual const char * getPreviousHash() const;
    virtual void setPreviousHash(const char * previousHash);

    virtual const char * getBlockHash() const;
    virtual void setBlockHash(const char * blockHash);

    virtual long getTimestamp() const;
    virtual void setTimestamp(long timestamp);

    virtual int getLastHeight() const;
    virtual void setLastHeight(int lastHeight);

    virtual void setEntriesArraySize(size_t size);
    virtual size_t getEntriesArraySize() const;
    virtual const ReportEntry& getEntries(size_t k) const;
    virtual ReportEntry& getEntriesForUpdate(size_t k) { return const_cast<ReportEntry&>(const_cast<SyncBlockMsg*>(this)->getEntries(k));}
    virtual void setEntries(size_t k, const ReportEntry& entries);
    virtual void insertEntries(size_t k, const ReportEntry& entries);
    [[deprecated]] void insertEntries(const ReportEntry& entries) {appendEntries(entries);}
    virtual void appendEntries(const ReportEntry& entries);
    virtual void eraseEntries(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SyncBlockMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SyncBlockMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:98</tt> by opp_msgtool.
 * <pre>
 * // device -> TopoManager：退出请求（可选）
 * message LeaveReq
 * {
 *     string SenderID;
 *     int deviceId;
 *     simtime_t sendTime;
 * }
 * </pre>
 */
class LeaveReq : public ::omnetpp::cMessage
{
  protected:
    opp_string SenderID;
    int deviceId = 0;
    simtime_t sendTime = SIMTIME_ZERO;

  private:
    void copy(const LeaveReq& other);

  protected:
    bool operator==(const LeaveReq&) = delete;

  public:
    LeaveReq(const char *name=nullptr, short kind=0);
    LeaveReq(const LeaveReq& other);
    virtual ~LeaveReq();
    LeaveReq& operator=(const LeaveReq& other);
    virtual LeaveReq *dup() const override {return new LeaveReq(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSenderID() const;
    virtual void setSenderID(const char * SenderID);

    virtual int getDeviceId() const;
    virtual void setDeviceId(int deviceId);

    virtual simtime_t getSendTime() const;
    virtual void setSendTime(simtime_t sendTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LeaveReq& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LeaveReq& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:105</tt> by opp_msgtool.
 * <pre>
 * // TopoManager -> device：退出确认（可选）
 * message LeaveAck
 * {
 *     string SenderID;
 *     int deviceId;
 *     simtime_t ackTime;
 * }
 * </pre>
 */
class LeaveAck : public ::omnetpp::cMessage
{
  protected:
    opp_string SenderID;
    int deviceId = 0;
    simtime_t ackTime = SIMTIME_ZERO;

  private:
    void copy(const LeaveAck& other);

  protected:
    bool operator==(const LeaveAck&) = delete;

  public:
    LeaveAck(const char *name=nullptr, short kind=0);
    LeaveAck(const LeaveAck& other);
    virtual ~LeaveAck();
    LeaveAck& operator=(const LeaveAck& other);
    virtual LeaveAck *dup() const override {return new LeaveAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSenderID() const;
    virtual void setSenderID(const char * SenderID);

    virtual int getDeviceId() const;
    virtual void setDeviceId(int deviceId);

    virtual simtime_t getAckTime() const;
    virtual void setAckTime(simtime_t ackTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LeaveAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LeaveAck& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:112</tt> by opp_msgtool.
 * <pre>
 * // peer -> TopoManager：退出请求（可选）
 * message PeerLeaveReq
 * {
 *     string SenderID;
 *     int peerId;
 *     simtime_t sendTime;
 * }
 * </pre>
 */
class PeerLeaveReq : public ::omnetpp::cMessage
{
  protected:
    opp_string SenderID;
    int peerId = 0;
    simtime_t sendTime = SIMTIME_ZERO;

  private:
    void copy(const PeerLeaveReq& other);

  protected:
    bool operator==(const PeerLeaveReq&) = delete;

  public:
    PeerLeaveReq(const char *name=nullptr, short kind=0);
    PeerLeaveReq(const PeerLeaveReq& other);
    virtual ~PeerLeaveReq();
    PeerLeaveReq& operator=(const PeerLeaveReq& other);
    virtual PeerLeaveReq *dup() const override {return new PeerLeaveReq(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSenderID() const;
    virtual void setSenderID(const char * SenderID);

    virtual int getPeerId() const;
    virtual void setPeerId(int peerId);

    virtual simtime_t getSendTime() const;
    virtual void setSendTime(simtime_t sendTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PeerLeaveReq& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PeerLeaveReq& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:118</tt> by opp_msgtool.
 * <pre>
 * message ReJoin
 * {
 *     int deviceId;
 *     simtime_t sendTime;   // 发送时刻（用于统计加入耗时）
 * }
 * </pre>
 */
class ReJoin : public ::omnetpp::cMessage
{
  protected:
    int deviceId = 0;
    simtime_t sendTime = SIMTIME_ZERO;

  private:
    void copy(const ReJoin& other);

  protected:
    bool operator==(const ReJoin&) = delete;

  public:
    ReJoin(const char *name=nullptr, short kind=0);
    ReJoin(const ReJoin& other);
    virtual ~ReJoin();
    ReJoin& operator=(const ReJoin& other);
    virtual ReJoin *dup() const override {return new ReJoin(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getDeviceId() const;
    virtual void setDeviceId(int deviceId);

    virtual simtime_t getSendTime() const;
    virtual void setSendTime(simtime_t sendTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ReJoin& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ReJoin& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:124</tt> by opp_msgtool.
 * <pre>
 * // TopoManager -> peer：退出确认（可选）
 * message PeerLeaveAck
 * {
 *     string SenderID;
 *     int peerId;
 *     simtime_t ackTime;
 * }
 * </pre>
 */
class PeerLeaveAck : public ::omnetpp::cMessage
{
  protected:
    opp_string SenderID;
    int peerId = 0;
    simtime_t ackTime = SIMTIME_ZERO;

  private:
    void copy(const PeerLeaveAck& other);

  protected:
    bool operator==(const PeerLeaveAck&) = delete;

  public:
    PeerLeaveAck(const char *name=nullptr, short kind=0);
    PeerLeaveAck(const PeerLeaveAck& other);
    virtual ~PeerLeaveAck();
    PeerLeaveAck& operator=(const PeerLeaveAck& other);
    virtual PeerLeaveAck *dup() const override {return new PeerLeaveAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSenderID() const;
    virtual void setSenderID(const char * SenderID);

    virtual int getPeerId() const;
    virtual void setPeerId(int peerId);

    virtual simtime_t getAckTime() const;
    virtual void setAckTime(simtime_t ackTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PeerLeaveAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PeerLeaveAck& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:130</tt> by opp_msgtool.
 * <pre>
 * message VerifyMessage
 * {
 *     ReportMessage rm;
 *     int state;
 * }
 * </pre>
 */
class VerifyMessage : public ::omnetpp::cMessage
{
  protected:
    ReportMessage rm;
    int state = 0;

  private:
    void copy(const VerifyMessage& other);

  protected:
    bool operator==(const VerifyMessage&) = delete;

  public:
    VerifyMessage(const char *name=nullptr, short kind=0);
    VerifyMessage(const VerifyMessage& other);
    virtual ~VerifyMessage();
    VerifyMessage& operator=(const VerifyMessage& other);
    virtual VerifyMessage *dup() const override {return new VerifyMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const ReportMessage& getRm() const;
    virtual ReportMessage& getRmForUpdate() { return const_cast<ReportMessage&>(const_cast<VerifyMessage*>(this)->getRm());}
    virtual void setRm(const ReportMessage& rm);

    virtual int getState() const;
    virtual void setState(int state);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const VerifyMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, VerifyMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:135</tt> by opp_msgtool.
 * <pre>
 * message PrePrepareMsg
 * {
 *     int viewNum;
 *     int seqNum;
 *     ReportMessage rm;
 *     int state;
 * }
 * </pre>
 */
class PrePrepareMsg : public ::omnetpp::cMessage
{
  protected:
    int viewNum = 0;
    int seqNum = 0;
    ReportMessage rm;
    int state = 0;

  private:
    void copy(const PrePrepareMsg& other);

  protected:
    bool operator==(const PrePrepareMsg&) = delete;

  public:
    PrePrepareMsg(const char *name=nullptr, short kind=0);
    PrePrepareMsg(const PrePrepareMsg& other);
    virtual ~PrePrepareMsg();
    PrePrepareMsg& operator=(const PrePrepareMsg& other);
    virtual PrePrepareMsg *dup() const override {return new PrePrepareMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getViewNum() const;
    virtual void setViewNum(int viewNum);

    virtual int getSeqNum() const;
    virtual void setSeqNum(int seqNum);

    virtual const ReportMessage& getRm() const;
    virtual ReportMessage& getRmForUpdate() { return const_cast<ReportMessage&>(const_cast<PrePrepareMsg*>(this)->getRm());}
    virtual void setRm(const ReportMessage& rm);

    virtual int getState() const;
    virtual void setState(int state);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PrePrepareMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PrePrepareMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:142</tt> by opp_msgtool.
 * <pre>
 * message PrepareMsg
 * {
 *     int viewNum;
 *     int seqNum;
 *     int orderId;
 *     ReportMessage rm;
 *     int state;
 * }
 * </pre>
 */
class PrepareMsg : public ::omnetpp::cMessage
{
  protected:
    int viewNum = 0;
    int seqNum = 0;
    int orderId = 0;
    ReportMessage rm;
    int state = 0;

  private:
    void copy(const PrepareMsg& other);

  protected:
    bool operator==(const PrepareMsg&) = delete;

  public:
    PrepareMsg(const char *name=nullptr, short kind=0);
    PrepareMsg(const PrepareMsg& other);
    virtual ~PrepareMsg();
    PrepareMsg& operator=(const PrepareMsg& other);
    virtual PrepareMsg *dup() const override {return new PrepareMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getViewNum() const;
    virtual void setViewNum(int viewNum);

    virtual int getSeqNum() const;
    virtual void setSeqNum(int seqNum);

    virtual int getOrderId() const;
    virtual void setOrderId(int orderId);

    virtual const ReportMessage& getRm() const;
    virtual ReportMessage& getRmForUpdate() { return const_cast<ReportMessage&>(const_cast<PrepareMsg*>(this)->getRm());}
    virtual void setRm(const ReportMessage& rm);

    virtual int getState() const;
    virtual void setState(int state);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PrepareMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PrepareMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:150</tt> by opp_msgtool.
 * <pre>
 * message CommitMsg
 * {
 *     int viewNum;
 *     int seqNum;
 *     int orderId;
 *     ReportMessage rm;
 *     int state;
 * }
 * </pre>
 */
class CommitMsg : public ::omnetpp::cMessage
{
  protected:
    int viewNum = 0;
    int seqNum = 0;
    int orderId = 0;
    ReportMessage rm;
    int state = 0;

  private:
    void copy(const CommitMsg& other);

  protected:
    bool operator==(const CommitMsg&) = delete;

  public:
    CommitMsg(const char *name=nullptr, short kind=0);
    CommitMsg(const CommitMsg& other);
    virtual ~CommitMsg();
    CommitMsg& operator=(const CommitMsg& other);
    virtual CommitMsg *dup() const override {return new CommitMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getViewNum() const;
    virtual void setViewNum(int viewNum);

    virtual int getSeqNum() const;
    virtual void setSeqNum(int seqNum);

    virtual int getOrderId() const;
    virtual void setOrderId(int orderId);

    virtual const ReportMessage& getRm() const;
    virtual ReportMessage& getRmForUpdate() { return const_cast<ReportMessage&>(const_cast<CommitMsg*>(this)->getRm());}
    virtual void setRm(const ReportMessage& rm);

    virtual int getState() const;
    virtual void setState(int state);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CommitMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CommitMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:158</tt> by opp_msgtool.
 * <pre>
 * message BlockMsg
 * {
 *     int blockNum;
 *     ReportMessage rm;
 *     simtime_t BlockTimestamp;
 *     int state;
 * }
 * </pre>
 */
class BlockMsg : public ::omnetpp::cMessage
{
  protected:
    int blockNum = 0;
    ReportMessage rm;
    simtime_t BlockTimestamp = SIMTIME_ZERO;
    int state = 0;

  private:
    void copy(const BlockMsg& other);

  protected:
    bool operator==(const BlockMsg&) = delete;

  public:
    BlockMsg(const char *name=nullptr, short kind=0);
    BlockMsg(const BlockMsg& other);
    virtual ~BlockMsg();
    BlockMsg& operator=(const BlockMsg& other);
    virtual BlockMsg *dup() const override {return new BlockMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getBlockNum() const;
    virtual void setBlockNum(int blockNum);

    virtual const ReportMessage& getRm() const;
    virtual ReportMessage& getRmForUpdate() { return const_cast<ReportMessage&>(const_cast<BlockMsg*>(this)->getRm());}
    virtual void setRm(const ReportMessage& rm);

    virtual simtime_t getBlockTimestamp() const;
    virtual void setBlockTimestamp(simtime_t BlockTimestamp);

    virtual int getState() const;
    virtual void setState(int state);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BlockMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BlockMsg& obj) {obj.parsimUnpack(b);}


}  // namespace omnetpp


namespace omnetpp {

template<> inline omnetpp::ReportMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::ReportMessage*>(ptr.get<cObject>()); }
template<> inline omnetpp::JoinReq *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::JoinReq*>(ptr.get<cObject>()); }
template<> inline omnetpp::JoinVerifyReq *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::JoinVerifyReq*>(ptr.get<cObject>()); }
template<> inline omnetpp::JoinAck *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::JoinAck*>(ptr.get<cObject>()); }
template<> inline omnetpp::PeerJoinReq *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::PeerJoinReq*>(ptr.get<cObject>()); }
template<> inline omnetpp::PeerJoinVerifyReq *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::PeerJoinVerifyReq*>(ptr.get<cObject>()); }
template<> inline omnetpp::PeerJoinAck *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::PeerJoinAck*>(ptr.get<cObject>()); }
template<> inline omnetpp::SyncLedgerReq *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::SyncLedgerReq*>(ptr.get<cObject>()); }
template<> inline omnetpp::ReportEntry *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::ReportEntry*>(ptr.get<cObject>()); }
template<> inline omnetpp::SyncBlockMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::SyncBlockMsg*>(ptr.get<cObject>()); }
template<> inline omnetpp::LeaveReq *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::LeaveReq*>(ptr.get<cObject>()); }
template<> inline omnetpp::LeaveAck *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::LeaveAck*>(ptr.get<cObject>()); }
template<> inline omnetpp::PeerLeaveReq *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::PeerLeaveReq*>(ptr.get<cObject>()); }
template<> inline omnetpp::ReJoin *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::ReJoin*>(ptr.get<cObject>()); }
template<> inline omnetpp::PeerLeaveAck *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::PeerLeaveAck*>(ptr.get<cObject>()); }
template<> inline omnetpp::VerifyMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::VerifyMessage*>(ptr.get<cObject>()); }
template<> inline omnetpp::PrePrepareMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::PrePrepareMsg*>(ptr.get<cObject>()); }
template<> inline omnetpp::PrepareMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::PrepareMsg*>(ptr.get<cObject>()); }
template<> inline omnetpp::CommitMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::CommitMsg*>(ptr.get<cObject>()); }
template<> inline omnetpp::BlockMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<omnetpp::BlockMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __OMNETPP_MESSAGE_M_H

